# -*- coding: utf-8 -*-
"""LLM_LangChain_Basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10o6prP_ffKMLQOvWZzxi_0hxpKAtmCpJ
"""

!pip install langchain openai

!pip install langchain_community

import openai
import os
from langchain import PromptTemplate
from langchain.llms import OpenAI
from langchain.chains import LLMChain

os.environ["OPENAI_API_KEY"] = 'sk-proj-Z1PPHJCTuwvrnfo4s69GT3BlbkFJLeWYsNc1McEQPUEw6dj7'

greet_temp="""write a greeting message for someone who just joined our community."""

prompt_template=PromptTemplate(input_variable=[],template=greet_temp)

from langchain.chat_models import ChatOpenAI
greet_llm=ChatOpenAI(temperature=0.5,model_name="gpt-3.5-turbo")

greet_chain=LLMChain(llm=greet_llm,prompt=prompt_template,output_key="greeting",verbose=True)

result=greet_chain({})
print(result["greeting"])